// Generated by CoffeeScript 1.12.6
(function() {
  var addEvent, addImage, buildEvent, buildTimelineHTML, buildVideoHTML, deleteEvent, ls, moveDown, moveSectionUp, moveUp, newDetail, removeDetail;

  ls = function(location) {
    var div, divs, k, len;
    if (location == null) {
      location = document;
    }
    divs = location.getElementsByTagName('div');
    for (k = 0, len = divs.length; k < len; k++) {
      div = divs[k];
      console.log("Id: " + (div.getAttribute('id')) + ", Class: " + (div.getAttribute('class')));
    }
  };

  $('#parse').on("click", function() {
    var event, events, feature, html, htmlContent, i, k, l, len, len1, m, pageType, section, sections, tempHTML;
    pageType = document.getElementById("type-of-page");
    html = document.getElementById("html");
    htmlContent = document.getElementById("html-content");
    if ((pageType.value != null) && (html.value != null)) {
      htmlContent.innerHTML = html.value;
      html.value = "";
      tempHTML = "";
      switch (pageType.value) {
        case "video":
          feature = htmlContent.getElementsByClassName('video-feature')[0];
          tempHTML += buildFeature(feature);
          sections = htmlContent.getElementsByClassName('video-section');
          for (k = 0, len = sections.length; k < len; k++) {
            section = sections[k];
            tempHTML += buildSection(section);
          }
          tempHTML += "<br /><button class='btn' id='build-video' onclick='buildVideoHTML()'>Build HTML</button>";
          break;
        case "timeline":
          events = htmlContent.getElementsByClassName('events-content')[0].getElementsByTagName('ol')[0].getElementsByTagName('li');
          for (l = 0, len1 = events.length; l < len1; l++) {
            event = events[l];
            tempHTML += buildEvent(event);
          }
          tempHTML += "<br /><button class='btn' id='build-timeline' onclick='buildTimelineHTML()'>Build HTML</button>";
          break;
        case "vert-timeline":
          tempHTML += buildVertTimeline(document.getElementsByClassName('container')[0]);
          tempHTML += "<br /><button class='btn' id='build-vert-timeline' onclick='buildVertTimelineHTML()'>Build HTML</button>";
          break;
        default:
          break;
      }
      document.getElementById("input-area").innerHTML = tempHTML;
    } else if (pageType == null) {
      alert("Select what type of page!");
    } else {
      htmlContent.innerHTML = html.value;
      html.value = "";
      tempHTML = "";
      switch (pageType.value) {
        case "video":
          tempHTML += "<div style='height: 610px;' class='feature-video champ-card'><h2>Feature Video</h2>";
          for (i = m = 0; m < 4; i = ++m) {
            if (!i % 2) {
              tempHTML += "<div style='float: left; margin: 15px; margin-left: 100px;' class='video-entry champ-card'>";
            } else {
              tempHTML += "<div style'float: left; margin: 15px;' class='video-entry champ-card'>";
            }
            if (!i) {
              tempHTML += "<h3>Feature Video Main Video</h3>";
            } else {
              tempHTML += "<h3>Feature Video Preview " + i + "</h3>";
            }
            tempHTML += "<p style='float: left'>URL:</p><input style='float: left' class='video-url'  /><br /><br />" + "<p style='float: left; padding-bottom: 0;'>Thumbnail URL:</p><input style='float: left' class='video-thumb-url'  />" + "<br /><p style='float:left; font-size: 10px; margin-top:0;'>Note: Make sure thumbnail is 16:9</p><br /><br />" + "<p style='float: left'>Description:</p><input style='float: left' class='video-description' maxlength='30'  />";
            "</div>";
            if (i % 2) {
              tempHTML += "<br/><br/>";
            }
          }
          tempHTML += "<button style='float: left; margin-left: 20px; margin-top: 10px;' class='btn' onclick='addNewSection(this)'>Add Section</button></div>";
          break;
        case "timeline":
          tempHTML += '<div class="event-entry champ-card">' + '<input maxlength="4"><br /><br />' + '<div><textarea></textarea><br />' + '<button class="btn" onclick="newDetail(this)">Add</button>' + '<button class="btn" onclick="removeDetail(this)" style="margin-left: 5px;">Remove</button>' + '<button class="btn" onclick="moveUp(this)" style="margin-left: 5px;">Up</button>' + '<button class="btn" onclick="moveDown(this)" style="margin-left: 5px;">Down</button>' + '<br /><br /></div>' + '<button class="btn" onclick="addEvent(this)">Add Event</button>' + '<button class="btn" onclick="deleteEvent(this)" style="margin-left: 5px;">Remove Event</button>' + '<button class="btn" onclick="moveUp(this)" style="margin-left: 5px;">Up</button>' + '<button class="btn" onclick="moveDown(this)" style="margin-left: 5px;">Down</button>' + '<button class="btn" onclick="addImage(this)" style="margin-left: 5px;">Add Image</button>' + '</div>' + '<br /><button class=\"btn\" id=\"build-timeline\" onclick=\"buildTimelineHTML()\">Build HTML</button>';
          break;
        case "vert-timeline":
          tempHTML += '<br/><button class="btn" onclick="addCoverPhoto(this)">Add Cover Photo</button><br/>' + '<div class="event-element champ-card"><input class="event-element-header" type="text"><br /><br />' + '<div><textarea class="event-element-point"></textarea>' + '<br/><button class="btn" style="margin-left: 5px" onclick="addElement(this)">Add Detail</button>' + '<button class="btn" style="margin-left: 5px" onclick="removeDetail(this)">Remove Detail</button>' + '<button class="btn" style="margin-left: 5px" onclick="moveUp(this)">Move Up</button>' + '<button class="btn" style="margin-left: 5px" onclick="moveDown(this)">Move Down</button>' + '<br/><br/></div>' + '<button class="btn" style="margin-left: 5px" onclick="addTimelineElement(this)">Add Event</button>' + '<button class="btn" style="margin-left: 5px" onclick="deleteEvent(this)">Remove Event</button>' + '<button class="btn" style="margin-left: 5px" onclick="moveUp(this)">Move Up</button>' + '<button class="btn" style="margin-left: 5px" onclick="moveDown(this)">Move Down</button></div>';
          break;
        default:
          break;
      }
      document.getElementById("input-area").innerHTML = tempHTML;
    }
  });

  buildEvent = function(event) {
    var html, k, len, point, points, year;
    html = "<div class='event-entry champ-card'>";
    year = event.getElementByTagName('h2')[0].innerHTML;
    html += '<input maxlength="4" value="' + year + '"><br /><br />';
    if (event.getElementsByTagName('img').length) {
      html += '<div><h3 style="float: left; margin-bottom: 0;">Image Address: </h3><input style="margin-bottom: 0" class="timeline-image"' + ' value="' + event.getElementsByTagName('img')[0].getAttribute('src') + '"><br />' + '<button style="clear: left; float: left; margin-top: 0" class="btn" onclick="deleteEvent(this)">Remove Image</button><br /><br /><br /></div>';
    }
    points = event.getElementsByTagName('p');
    for (k = 0, len = points.length; k < len; k++) {
      point = points[k];
      html += '<div><textarea>#{point.innerHTML}</textarea>' + '<br /><button class="btn" onclick="newDetail(this)">Add</button>' + '<button class="btn" onclick="removeDetail(this)" style="margin-left: 5px;">Remove</button>' + '<button class="btn" onclick="moveUp(this)" style="margin-left: 5px;">Up</button>' + '<button class="btn" onclick="moveDown(this)" style="margin-left: 5px;">Down</button>' + '<br /><br /></div>';
    }
    html += '<button class="btn" onclick="addEvent(this)">Add Event</button>' + '<button class="btn" onclick="deleteEvent(this)" style="margin-left: 5px;">Remove Event</button>' + '<button class="btn" onclick="moveUp(this)" style="margin-left: 5px;">Up</button>' + '<button class="btn" onclick="moveDown(this)" style="margin-left: 5px;">Down</button>' + '<button class="btn" onclick="addImage(this)" style="margin-left: 5px;">Add Image</button>' + '</div>';
    return html;
  };

  moveUp = function(button) {
    var prevElement;
    prevElement = $(button.parentElement).prev();
    if ($(button.parentElement).prop("tagName") === $(prevElement).prop("tagName")) {
      $(button.parentElement).detach().insertBefore(prevElement);
    }
  };

  moveSectionUp = function(button) {
    var prevElement;
    prevElement = $(button.parentElement).prev();
    if ($(prevElement).hasClass('section-video')) {
      $(button.parentElement).detach().insertBefore(prevElement);
    }
  };

  moveDown = function(button) {
    var nextElement;
    nextElement = $(button.parentElement).next();
    if ($(button.parentElement).prop("tagName") === $(nextElement).prop("tagName")) {
      $(button.parentElement).detach().insertAfter(nextElement);
    }
  };

  addEvent = function(button) {
    $('<div class="event-entry champ-card">' + '<input maxlength="4"><br /><br />' + '<div><textarea></textarea><br />' + '<button class="btn" onclick="newDetail(this)">Add</button>' + '<button class="btn" onclick="removeDetail(this)" style="margin-left: 5px;">Remove</button>' + '<button class="btn" onclick="moveUp(this)" style="margin-left: 5px;">Up</button>' + '<button class="btn" onclick="moveDown(this)" style="margin-left: 5px;">Down</button>' + '<br /><br /></div>' + '<button class="btn" onclick="addEvent(this)">Add Event</button>' + '<button class="btn" onclick="deleteEvent(this)" style="margin-left: 5px;">Remove Event</button>' + '<button class="btn" onclick="moveUp(this)" style="margin-left: 5px;">Up</button>' + '<button class="btn" onclick="moveDown(this)" style="margin-left: 5px;">Down</button>' + '<button class="btn" onclick="addImage(this)" style="margin-left: 5px;">Add Image</button>' + '</div>').insertAfter(button.parentElement);
  };

  addImage = function(button) {
    if (!button.parentElement.getElementsByTagName('h3').length) {
      $('<div><h3 style="float: left; margin-bottom: 0;">Image Address: </h3><input style="margin-bottom: 0" class="timeline-image"><br />' + '<button style="clear: left; float: left; margin-top: 0" class="btn" onclick="deleteEvent(this)">Remove Image</button><br /><br /><br /></div>').insertAfter($(button.parentElement.getElementsByTagName('input')[0]).next().next());
    }
  };

  deleteEvent = function(button) {
    $(button.parentElement).remove();
  };

  newDetail = function(button) {
    $('<div><textarea></textarea><br />' + '<button class="btn" onclick="newDetail(this)">Add</button>' + '<button class="btn" onclick="removeDetail(this)" style="margin-left: 5px;">Remove</button>' + '<button class="btn" onclick="moveUp(this)" style="margin-left: 5px;">Up</button>' + '<button class="btn" onclick="moveDown(this)" style="margin-left: 5px;">Down</button>' + '<br /><br /></div>').insertAfter(button.parentElement);
  };

  removeDetail = function(button) {
    if (button.parentElement.parentElement.getElementsByTagName('textarea').length >= 2) {
      $(button.parentElement).remove();
    }
  };

  buildTimelineHTML = function() {
    var currentEvent, events, i, k, l, len, m, point, ref, ref1, ref2, tempHTML, timelineHTML;
    timelineHTML = document.getElementById("timeline-html");
    events = document.getElementsByClassName('event-entry');
    tempHTML = "<ol>";
    for (i = k = 0, ref = events.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
      currentEvent = events[i].getElementsByTagName('input')[0].value;
      if (!i) {
        tempHTML += '<li><a href=\"#0\" data-date=\"01/01/' + currentEvent + '\" class=\"selected\">' + currentEvent + '</a></li>';
      } else {
        tempHTML += '<li><a href=\"#0\" data-date=\"01/01/' + currentEvent + '\">' + currentEvent + '</a></li>';
      }
    }
    tempHTML += '</ol><span class=\"filling-line\" aria-hidden=\"true\"></span>';
    timelineHTML.getElementsByClassName('events')[0].innerHTML = tempHTML;
    tempHTML = "";
    for (i = l = 0, ref1 = events.length; 0 <= ref1 ? l < ref1 : l > ref1; i = 0 <= ref1 ? ++l : --l) {
      currentEvent = events[i].getElementsByTagName('input')[0].value;
      if (!i) {
        tempHTML += '<li class=\"selected\" data-date=\"01/01/' + currentEvent + '\">';
      } else {
        tempHTML += '<li data-date=\"01/01/' + currentEvent + '\">';
      }
      tempHTML += '<h2>' + currentEvent + '</h2>';
      if (events[i].getElementsByTagName('h3').length) {
        tempHTML += '<img src="' + events[i].getElementsByTagName('input')[1].value + '" style="width: 100%; height: auto;" /><br /><br />';
      }
      ref2 = events[i].getElementsByTagName('textarea');
      for (m = 0, len = ref2.length; m < len; m++) {
        point = ref2[m];
        tempHTML += '<p>' + point.value + '</p><br />';
      }
      tempHTML += '</li>';
    }
    timelineHTML.getElementsByClassName('events-content')[0].getElementsByTagName('ol')[0].innerHTML = tempHTML;
    $("<br /><br /><textarea id=\"output-html\"></textarea>").insertAfter('#build-timeline');
    document.getElementById("output-html").value = timelineHTML.innerHTML;
  };

  buildVideoHTML = function() {
    var entries, feats, featsConContent, htmlOutput, i, j, k, l, m, ref, sections, videoHTML;
    videoHTML = document.getElementById('video-page-html');
    feats = videoHTML.getElementsByClassName('video-feature')[0].getElementsByClassName('feat-objects');
    featsConContent = document.getElementsByClassName('feature-video')[0].getElementsByClassName('video-entry');
    for (i = k = 0; k < 4; i = ++k) {
      feats[i].innerHTML = '<p class="video-url">' + featsConContent[i].getElementsByClassName('video-url')[0].value + '</p>' + '<p class="thumbnail-url">' + featsConContent[i].getElementsByClassName('video-thumb-url')[0].value + '</p>' + '<p class="video-description">' + featsConContent[i].getElementsByClassName('video-description')[0].value + '</p>';
    }
    htmlOutput = videoHTML.innerHTML;
    sections = document.getElementsByClassName('section-video');
    for (i = l = 0, ref = sections.length; 0 <= ref ? l < ref : l > ref; i = 0 <= ref ? ++l : --l) {
      htmlOutput += '<div class="video-section champ-card">' + '<div class="section-panel-left">' + '<h2>' + sections[i].getElementsByClassName('section-title')[0].value + '</h2><br />' + '<div class="video-section-main video"></div>' + '</div>' + '<div class="section-panel-right"></div>';
      entries = sections[i].getElementsByClassName('video-entry');
      for (j = m = 0; m < 4; j = ++m) {
        htmlOutput += '<div class="video-section-object">' + '<p class="video-url-section">' + entries[j].getElementsByClassName('video-url')[0].value + '</p>' + '<p class="thumbnail-url-section">' + entries[j].getElementsByClassName('video-thumb-url')[0].value + '</p>' + '<p class="video-description-section">' + entries[j].getElementsByClassName('video-description')[0].value + '</p>' + '</div>';
      }
      htmlOutput += '</div><br /><br />';
    }
    $("<br /><br /><textarea id=\"output-html\"></textarea>").insertAfter('#build-video');
    return document.getElementById("output-html").value = htmlOutput;
  };

}).call(this);

//# sourceMappingURL=script.js.map
